FROM scratch
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY ./target/oxeye-backend /oxeye-backend
ENV DATABASE_PATH=/oxeye.db
ENV PORT=3000
EXPOSE 3000
ENTRYPOINT ["/oxeye-backend"]
